DROP TABLE IF EXISTS tutorials;
CREATE TABLE tutorials
(
    BRAND_ID    LONG NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST LONG NOT NULL,
    PRODUCT_ID VARCHAR2(20) NOT NULL,
    PRIORITY LONG NOT NULL,
    PRICE FLOAT NOT NULL,
    CURR VARCHAR2(20) NOT NULL,
    CONSTRAINT tutorials_pk PRIMARY KEY (BRAND_ID, PRICE_LIST, PRODUCT_ID)
);
